version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5300:5300"  # Host:Container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8500:8500"  # Host:Container
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8500 --reload
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  app-network:
    driver: bridge