version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5300:80"  # Host:Container
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8500:8500"  # Host:Container
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  app-network:
    driver: bridge